# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed144e9617558ca27155fe2e918b1834f335d2b99292dab5e2ee63cd88be7ebc0594e29a40fd9f475ac462ef5a40b35b964f7d025ca75c1dbe5995b143e27ec1

test:
  secret_key_base: 82da41438138e093e49564f2a7947648af3f5d9c563faaf3a38d34bb7673ace262ec1ce19a8c0f7e86b14f304cd3c0ab35e86331e2a4a62006c6828ba260d804

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
